In [1]:
import numpy as np

In [2]:
a=np.array([4,5,6])
print (a)

[4 5 6]


In [3]:
a=np.array([(4,5,6),(2,3,4)])
print (a)

[[4 5 6]
 [2 3 4]]


In [4]:
a1=np.linspace(1,10,6)
print (a1)

[ 1.   2.8  4.6  6.4  8.2 10. ]


In [5]:
print(a.ndim)

2


In [6]:
print (a.dtype)

int64


In [7]:
print(a.size)
print(a1.size)

6
6


In [8]:
print(a.shape)

(2, 3)


In [9]:
print(a)

[[4 5 6]
 [2 3 4]]


In [10]:
print(a.reshape(-3,2))

[[4 5]
 [6 2]
 [3 4]]


In [11]:
print(a.reshape(3,-2))

[[4 5]
 [6 2]
 [3 4]]


In [12]:
print (a)

[[4 5 6]
 [2 3 4]]


In [13]:
print(a[0,2])

6


In [14]:
print (a[1,2])

4


In [15]:
print (a[0:,2])

[6 4]


In [16]:
print (a[:,2])

[6 4]


In [17]:
a=np.array([(1,2,3),(2,3,4),(3,4,5),(4,5,6)])
print (a[0:,2])

[3 4 5 6]


In [18]:
print(a[0:2,1])

[2 3]


In [19]:
print(a.min())
print(a.max())
print(a.sum())

1
6
42


In [21]:
print(a.sum(axis=0))

[10 14 18]


In [22]:
print(a.sum(axis=1))

[ 6  9 12 15]


In [23]:
print (a+a)

[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]
 [ 8 10 12]]


In [24]:
print (a-a)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
print (a*a)

[[ 1  4  9]
 [ 4  9 16]
 [ 9 16 25]
 [16 25 36]]


In [26]:
a = np.arange(1, 11)  # We are creating an array contains n = 10 elements
lengthA = len(a)

# splitting of terms for easiness
sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2

# Implementation of formula
# np.rint is used for rounding off to integer
Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))  # np.rint is used for rounding off to integer
print("The first {} numbers of Fibonacci series are {} . ".format(lengthA, Fn))

The first 10 numbers of Fibonacci series are [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.] . 


In [28]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 7, 8])

print(array1)   # Original array1
print(array2)   # Original array2

print("\nCovariance matrix of the said arrays:\n",   # Covariance matrix
	np.cov(array1, array2))


[1 2 3]
[4 7 8]

Covariance matrix of the said arrays:
 [[1.         2.        ]
 [2.         4.33333333]]
